FROM node:21-alpine
ENV NEXT_PUBLIC_API_ENDPOINT=${NEXT_PUBLIC_API_ENDPOINT}
ENV NEXT_PUBLIC_SECRET=${NEXT_PUBLIC_SECRET}
WORKDIR /app
COPY ./blocks-cli/package.json ./
RUN yarn install --production
COPY ./blocks-cli/ .
RUN yarn add typescript tsc ts-node && yarn build
CMD ["yarn", "start"]
EXPOSE 3000